linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*database/sql.Tx).Rollback
      - (io.Closer).Close
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/product_review_hub
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
  misspell:
    locale: US
  nolintlint:
    require-explanation: true
    require-specific: true
  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  staticcheck:
    checks: ["all"]

linters:
  disable-all: true
  enable:
    - errcheck         # проверка обработки ошибок
    - gofmt            
    - goimports        
    - gosec            
    - gosimple         
    - govet            
    - ineffassign      
    - misspell         
    - staticcheck      
    - typecheck        
    - unconvert        
    - unused           
    - whitespace       

  exclude-rules:
    - path: cmd/
      text: "should have comment or be unexported"
    - path: internal/handler/product_handler\.go
      text: "method GetProductById should be GetProductByID"
    - path: tests/
      linters:
        - dupl
        - shadow
        - goconst
        - gocyclo
        - revive
        - bodyclose
        - gocritic
        - errcheck
    - path: _test\.go
      linters:
        - dupl
        - shadow
        - goconst
        - gocyclo
        - errcheck
    - linters:
        - govet
      text: "fieldalignment:"
    - linters:
        - gocritic
      text: "hugeParam:"
    - path: cmd/
      linters:
        - gocritic
      text: "exitAfterDefer:"
    - linters:
        - govet
      text: "shadow:"
    - linters:
        - gocritic
      text: "(paramTypeCombine|unnamedResult|ifElseChain):"
    - text: "Error return value of .* is not checked"
      linters:
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
  exclude-dirs:
    - bin
    - vendor

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
