linters-settings:
  dupl:
    threshold: 100
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/product_review_hub
  govet:
    check-shadowing: true
    enable-all: true
  misspell:
    locale: US
  nolintlint:
    require-explanation: true
    require-specific: true
  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  staticcheck:
    checks: ["all"]

linters:
  disable-all: true
  enable:
    - bodyclose        # проверка закрытия HTTP body
    - dupl             # обнаружение дублирующегося кода
    - errcheck         # проверка обработки ошибок
    - exportloopref    # проверка ссылок на переменные цикла
    - goconst          # обнаружение повторяющихся строк для замены на константы
    - gocritic         # мета-линтер с множеством проверок
    - gocyclo          # проверка цикломатической сложности
    - gofmt            # проверка форматирования
    - goimports        # проверка импортов
    - gosec            # проверка безопасности
    - gosimple         # упрощение кода
    - govet            # стандартный go vet
    - ineffassign      # обнаружение неэффективных присваиваний
    - misspell         # проверка орфографии
    - nolintlint       # проверка директив nolint
    - revive           # быстрая альтернатива golint
    - staticcheck      # большой набор статических проверок
    - stylecheck       # проверка стиля кода
    - typecheck        # проверка типов
    - unconvert        # проверка ненужных преобразований типов
    - unparam          # обнаружение неиспользуемых параметров функций
    - unused           # обнаружение неиспользуемого кода
    - whitespace       # проверка пробелов

issues:
  exclude-rules:
    # Исключения для сгенерированного кода
    - path: internal/api/generated\.go
      linters:
        - revive
        - stylecheck
        - gosec
        - dupl
        - gocritic
    # Исключения для main.go
    - path: cmd/
      text: "should have comment or be unexported"
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - bin
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
